services:
  # 服务名称
  deepclaude:
    # 使用本地Dockerfile构建镜像
    build: .
    
    # 端口映射配置 - 与.env中PORT一致
    ports:
      - "1124:1124"
    
    # 环境变量配置 - 使用.env文件
    env_file:
      - .env
    
    # 额外的必要环境变量
    environment:
      - HOST=0.0.0.0
    
    # 容器重启策略
    restart: always
    
    # 卷挂载，保存持久化数据
    volumes:
      - ./:/app